test_absolute (__main__.TestExercice) ... FAIL
test_factorial (__main__.TestExercice) ... FAIL
test_prefixes (__main__.TestExercice) ... FAIL
test_summation (__main__.TestExercice) ... FAIL
test_verify_ages (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_absolute (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\harry\OneDrive\Documents\GitHub\chapitre-05-1-Hundrick974\test_exercice.py", line 19, in test_absolute
    self.assertListEqual(
AssertionError: Lists differ: [0, 0] != [5, 5]

First differing element 0:
0
5

- [0, 0]
+ [5, 5] : Mauvaise réponse

======================================================================
FAIL: test_factorial (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\harry\OneDrive\Documents\GitHub\chapitre-05-1-Hundrick974\test_exercice.py", line 59, in test_factorial
    self.assertListEqual(
AssertionError: Lists differ: [0, 0, 0, 0] != [1, 6, 40320, 3628800]

First differing element 0:
0
1

- [0, 0, 0, 0]
+ [1, 6, 40320, 3628800] : Mauvaise réponse

======================================================================
FAIL: test_prefixes (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\harry\OneDrive\Documents\GitHub\chapitre-05-1-Hundrick974\test_exercice.py", line 29, in test_prefixes
    self.assertListEqual(
AssertionError: Lists differ: [''] != ['Jack', 'Kack', 'Lack', 'Mack', 'Nack', 'Oack', 'Pack', 'Qack']

First differing element 0:
''
'Jack'

Second list contains 7 additional elements.
First extra element 1:
'Kack'

- ['']
+ ['Jack', 'Kack', 'Lack', 'Mack', 'Nack', 'Oack', 'Pack', 'Qack'] : Mauvaise réponse

======================================================================
FAIL: test_summation (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\harry\OneDrive\Documents\GitHub\chapitre-05-1-Hundrick974\test_exercice.py", line 47, in test_summation
    self.assertEqual(
AssertionError: 0 != 24133 : Mauvaise réponse

======================================================================
FAIL: test_verify_ages (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\harry\OneDrive\Documents\GitHub\chapitre-05-1-Hundrick974\test_exercice.py", line 74, in test_verify_ages
    self.assertListEqual(
AssertionError: Lists differ: [['True', 'True', 'False', 'False', 'True', 'True', 'True', 'True', 'False']] != [False, True, False, False, True, True, True, True, False]

First differing element 0:
['True', 'True', 'False', 'False', 'True', 'True', 'True', 'True', 'False']
False

Second list contains 8 additional elements.
First extra element 1:
True

- [['True', 'True', 'False', 'False', 'True', 'True', 'True', 'True', 'False']]
+ [False, True, False, False, True, True, True, True, False] : Mauvaise réponse

----------------------------------------------------------------------
Ran 5 tests in 0.010s

FAILED (failures=5)
